services: 
  api:
    image: jusan-fastapi-final:dockerized
    container_name: jusan-compose-final
    ports:
      - 8080:8080
    restart: on-failure
  nginx:
    image: nginx:mainline
    container_name: jusan-nginx-final
    ports:
      - 8787:80
    volumes:
      - ./jusan-docker-mount.conf:/etc/nginx/conf.d/default.conf  
      - ./jusan-fastapi-final.conf:/etc/nginx/conf.d/jusan-fastapi-final.conf
      - ./jusan-docker-mount:/var/www/example.com
    depends_on:
      - api
    restart: on-failure