---
- name: Configure NGINX servers
  hosts: lb
  become: yes

  handlers:
    - name: reload-nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

  tasks:
    - name: Install NGINX
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Copy main nginx.conf
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        notify: reload-nginx

    - name: Remove default.conf
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Debug loop variables
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - server_port: 7070
          server_name: jmart-ansible.kz
          locations:
            - path: /main
              status_code: 200
              message: Добро пожаловать на JMart!
            - path: /profile
              status_code: 201
              message: Это страница профиля.

        - server_port: 8080
          server_name: jusan-ansible.kz
          locations:
            - path: /
              status_code: 200
              message: Добро пожаловать на Jusan Bank!
            - path: /account
              status_code: 202
              message: Здесь ваш банковский счет!

        - server_port: 9090
          server_name: invest-ansible.kz
          locations:
            - path: /home
              status_code: 200
              message: Добро пожаловать на Jusan Invest!
            - path: /user
              status_code: 203
              message: Это страница с вашим брокерским счетом.

    - name: Create custom server configurations
      ansible.builtin.template:
        src: templates/server.conf.j2
        dest: /etc/nginx/conf.d/{{ item.server_name }}.conf
      loop:
        - server_port: 7070
          server_name: jmart-ansible.kz
          locations:
            - path: /main
              status_code: 200
              message: Добро пожаловать на JMart!
            - path: /profile
              status_code: 201
              message: Это страница профиля.

        - server_port: 8080
          server_name: jusan-ansible.kz
          locations:
            - path: /
              status_code: 200
              message: Добро пожаловать на Jusan Bank!
            - path: /account
              status_code: 202
              message: Здесь ваш банковский счет!

        - server_port: 9090
          server_name: invest-ansible.kz
          locations:
            - path: /home
              status_code: 200
              message: Добро пожаловать на Jusan Invest!
            - path: /user
              status_code: 203
              message: Это страница с вашим брокерским счетом.
      notify: reload-nginx
