services:
  local-vps-22:
    image: atlekbai/local-vps:latest
    container_name: local-vps-22
    ports:
      - "2222:22"
      - "8085:80"
      - "7075:7075"
      - "8086:8086"
      - "8888:8888"
      - "9095:9095"
    restart: always
    command: "22"
    volumes:
      - "~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro"

  local-vps-23:
    image: atlekbai/local-vps:latest
    container_name: local-vps-23
    ports:
      - "23:23"
    restart: always
    command: "23"
    volumes:
      - "~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro"

  local-vps-24:
    image: atlekbai/local-vps:latest
    container_name: local-vps-24
    ports:
      - "24:24"
    restart: always
    command: "24"
    volumes:
      - "~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro"