{
 "title": "API dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP average duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(http_requests_milliseconds_sum[5m])) by (endpoint)",
     "legendFormat": "/{{endpoint}}"
    }
   ]
  },
  {
   "title": "Calculator Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(errors_calculator_total[5m])",
     "legendFormat": "/calculator"
    }
   ]
  },
  {
   "title": "Last Values",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_sum_n", "legendFormat": "Sum1n" },
    { "expr": "last_fibo", "legendFormat": "Fibo" },
    { "expr": "list_size", "legendFormat": "List size" },
    { "expr": "last_calculator", "legendFormat": "Calculator" }
   ]
  },
  {
   "title": "HTTP requests per route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "last_over_time(http_requests_total[5m])",
     "legendFormat": "/{{endpoint}}"
    }
   ]
  }
 ]
}