---
- name: Download API binary
  get_url:
    url: https://github.com/jusan-singularity/track-devops-systemd-api/releases/download/v0.1/api
    dest: /tmp/api
    mode: '0755'

- name: Copy API service file
  copy:
    src: files/api.service
    dest: /etc/systemd/system/api.service
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload
  register: daemon_reload
  ignore_errors: yes

- name: Enable and start API service
  systemd:
    name: api.service
    state: started
    enabled: yes
